"use client"

import { useState, useEffect } from "react"
import { Loader2 } from "lucide-react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  buildImagePrompt,
  MOOD_MODIFIERS,
  VISUAL_STYLE_LABELS,
  VISUAL_STYLE_DESCRIPTIONS,
} from "@/lib/prompts/image-prompt-builder"
import type { Shot, ShotMood, VisualStyle } from "@prisma/client"

// Use serialized types where Decimal is converted to number for client components
type SerializedShot = Omit<Shot, "duration"> & { duration: number }

interface PromptEditorProps {
  shot: SerializedShot | null
  aspectRatio: "LANDSCAPE" | "PORTRAIT"
  open: boolean
  onOpenChange: (open: boolean) => void
  onSave: (
    shotId: string,
    updates: { description?: string; mood?: ShotMood; visualStyle?: VisualStyle }
  ) => void
  onGenerate: (shotId: string, customPrompt?: string, regenerate?: boolean) => void
  isGenerating?: boolean
}

const moodOptions: { value: ShotMood; label: string }[] = [
  { value: "DRAMATIC", label: "Dramatic" },
  { value: "PEACEFUL", label: "Peaceful" },
  { value: "APOCALYPTIC", label: "Apocalyptic" },
  { value: "DIVINE", label: "Divine" },
  { value: "FOREBODING", label: "Foreboding" },
  { value: "ACTION", label: "Action" },
]

const visualStyleOptions: { value: VisualStyle; label: string; description: string }[] = [
  { value: "PHOTOREALISTIC", label: "Photorealistic", description: "Real photography with natural skin texture" },
  { value: "HYPERREALISTIC_CINEMATIC", label: "Hyperrealistic Cinematic", description: "Hollywood film still aesthetic" },
  { value: "DRAMATIC_REALISM", label: "Dramatic Realism", description: "Gritty photojournalism style" },
  { value: "EPIC_FILM_STILL", label: "Epic Film Still", description: "70mm IMAX epic film look" },
  { value: "PAINTERLY_ARTISTIC", label: "Painterly/Artistic", description: "Digital painting style" },
  { value: "ANIMATED_STYLIZED", label: "Animated/Stylized", description: "3D Pixar-like style" },
]

export function PromptEditor({
  shot,
  aspectRatio,
  open,
  onOpenChange,
  onSave,
  onGenerate,
  isGenerating = false,
}: PromptEditorProps) {
  const [description, setDescription] = useState("")
  const [mood, setMood] = useState<ShotMood>("DRAMATIC")
  const [visualStyle, setVisualStyle] = useState<VisualStyle>("PHOTOREALISTIC")
  const [useCustomPrompt, setUseCustomPrompt] = useState(false)
  const [customPrompt, setCustomPrompt] = useState("")

  const autoGeneratedPrompt = buildImagePrompt({
    description,
    mood,
    visualStyle,
    aspectRatio,
  })

  useEffect(() => {
    if (shot) {
      setDescription(shot.description)
      setMood(shot.mood)
      setVisualStyle(shot.visualStyle || "PHOTOREALISTIC")
      setUseCustomPrompt(false)
      setCustomPrompt("")
    }
  }, [shot])

  // Update custom prompt when auto-generated prompt changes (if not in custom mode)
  useEffect(() => {
    if (!useCustomPrompt) {
      setCustomPrompt(autoGeneratedPrompt)
    }
  }, [autoGeneratedPrompt, useCustomPrompt])

  if (!shot) return null

  const finalPrompt = useCustomPrompt ? customPrompt : autoGeneratedPrompt

  const handleSaveAndGenerate = () => {
    onSave(shot.id, { description, mood, visualStyle })
    // Pass regenerate: true to delete existing images and generate new ones
    onGenerate(shot.id, finalPrompt, true)
    onOpenChange(false) // Close the modal
  }

  const handleSaveOnly = () => {
    onSave(shot.id, { description, mood, visualStyle })
    onOpenChange(false)
  }

  const selectedStyleDescription = VISUAL_STYLE_DESCRIPTIONS[visualStyle]

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            Edit Prompt
            <Badge variant="secondary">Shot {shot.shotIndex + 1}</Badge>
          </DialogTitle>
          <DialogDescription>
            Customize the shot description and settings for image generation.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* Description */}
          <div>
            <label className="text-sm font-medium text-[#2d2d2d] mb-2 block">
              Shot Description
            </label>
            <Textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="min-h-[100px]"
              placeholder="Describe what the camera sees..."
            />
          </div>

          {/* Mood & Visual Style */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="text-sm font-medium text-[#2d2d2d] mb-2 block">
                Mood
              </label>
              <Select
                value={mood}
                onValueChange={(value) => setMood(value as ShotMood)}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {moodOptions.map((option) => (
                    <SelectItem key={option.value} value={option.value}>
                      {option.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <p className="mt-1 text-xs text-[#6b6b6b]">
                {MOOD_MODIFIERS[mood].slice(0, 50)}...
              </p>
            </div>

            <div>
              <label className="text-sm font-medium text-[#2d2d2d] mb-2 block">
                Visual Style
              </label>
              <Select
                value={visualStyle}
                onValueChange={(value) => setVisualStyle(value as VisualStyle)}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {visualStyleOptions.map((option) => (
                    <SelectItem key={option.value} value={option.value}>
                      {option.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <p className="mt-1 text-xs text-[#6b6b6b]">
                {selectedStyleDescription}
              </p>
            </div>
          </div>

          {/* Generated Prompt Preview */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="text-sm font-medium text-[#2d2d2d]">
                {useCustomPrompt ? "Custom Prompt" : "Generated Prompt Preview"}
              </label>
              <button
                type="button"
                onClick={() => {
                  if (!useCustomPrompt) {
                    setCustomPrompt(autoGeneratedPrompt)
                  }
                  setUseCustomPrompt(!useCustomPrompt)
                }}
                className="text-xs text-accent hover:text-accent-light underline"
              >
                {useCustomPrompt ? "Use auto-generated" : "Edit manually"}
              </button>
            </div>
            {useCustomPrompt ? (
              <Textarea
                value={customPrompt}
                onChange={(e) => setCustomPrompt(e.target.value)}
                className="min-h-[120px] font-mono text-xs"
                placeholder="Enter your custom prompt..."
              />
            ) : (
              <div className="rounded-md bg-primary/5 p-3 max-h-[120px] overflow-auto">
                <p className="text-xs text-[#6b6b6b] font-mono whitespace-pre-wrap">
                  {autoGeneratedPrompt}
                </p>
              </div>
            )}
            {useCustomPrompt && (
              <p className="mt-1 text-xs text-[#6b6b6b]">
                You have full control over the prompt sent to GPT Image.
              </p>
            )}
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={handleSaveOnly} disabled={isGenerating}>
            Save Changes
          </Button>
          <Button
            variant="secondary"
            onClick={handleSaveAndGenerate}
            disabled={isGenerating}
          >
            {isGenerating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              "Save & Generate"
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
